# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161112_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracheque',
            name='exercicio',
            field=models.IntegerField(verbose_name='Exercício'),
        ),
        migrations.AlterField(
            model_name='contracheque',
            name='mes',
            field=models.IntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='municipio',
            field=models.CharField(choices=[('001', 'Trajano de Moraes')], max_length=100, verbose_name='Município'),
        ),
    ]
