# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170202_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracheque',
            options={'verbose_name': 'contra cheque', 'verbose_name_plural': 'contra cheques'},
        ),
        migrations.AlterModelOptions(
            name='gestor',
            options={'verbose_name': 'gestor', 'verbose_name_plural': 'gestores'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ('numero',), 'verbose_name': 'matrícula', 'verbose_name_plural': 'matrículas'},
        ),
        migrations.AlterModelOptions(
            name='orgao',
            options={'ordering': ('sigla',), 'verbose_name': 'orgão', 'verbose_name_plural': 'orgãos'},
        ),
        migrations.AddField(
            model_name='gestor',
            name='alterarSenhaUsuarios',
            field=models.BooleanField(default=False, verbose_name='Alterar Senha de Outros Usuários'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='municipio',
            field=models.CharField(choices=[('BOM_JARDIM', 'Bom Jardim'), ('CAMBUCI', 'Cambuci'), ('TRAJANO_DE_MORAES', 'Trajano de Moraes')], max_length=100, verbose_name='Município'),
        ),
    ]
